import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import Header from "@/app/components/Navbar";

import { cn } from "@/lib/utils"
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-[#030014] font-sans antialiased overflow-y-scroll overflow-x-hidden",
          fontSans.variable
        )}
      >
          {" "}
          <Header />
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
